# Generated by Django 3.2.8 on 2022-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='review',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
